### ISSUE TITLE
using `--gas=auto` causes zero division errors 

### ISSUE THREAD

**Issue by MSalopek** [skip-mev/feemarket#69]
During e2e testing it was discovered that using `--gas=auto` causes unexpected divide by zero errors.

## Reproducing the issue

`--gas=auto` sets the following [cosmos-sdk gas settings](https://github.com/cosmos/cosmos-sdk/blob/main/client/flags/flags.go#L187):
```sh
GasSetting {
  Simulate: true,
  Gas:      0,
}
```

The issue can reproduced by adding a test to `TestAnteHandle` in `x/feemarket/ante/fee_test.go`.
```go
func TestAnteHandle(t *testing.T) {
	// Same data for every test case
	gasLimit := antesuite.NewTestGasLimit()
	validFeeAmount := types.DefaultMinBaseFee.MulRaw(int64(gasLimit))
	validFee := sdk.NewCoins(sdk.NewCoin("stake", validFeeAmount))

	testCases := []antesuite.TestCase{
		// test --gas=auto flag settings
		// when --gas=auto is set, cosmos-sdk sets gas=0 and simulate=true
		{
			Name: "--gas=auto behaviour test",
			Malleate: func(suite *antesuite.TestSuite) antesuite.TestCaseArgs {
				accs := suite.CreateTestAccounts(1)

				return antesuite.TestCaseArgs{
					Msgs:      []sdk.Msg{testdata.NewTestMsg(accs[0].Account.GetAddress())},
					GasLimit:  0,
					FeeAmount: validFee,
				}
			},
			RunAnte:  true,
			RunPost:  false,
			Simulate: true,   // setting simulate=true and using gas=0 corresponds to "--gas=auto" cli flag
			ExpPass:  false,
			ExpErr:   sdkerrors.ErrInvalidGasLimit,
		},
 }
```

To confirm the issue using an app binary please run this command:
```shell
feemarketd tx bank send   cosmos1tw4w4x9098uvqxd822yk3afdxeeks9gnlupey7 cosmos149307pkt63453ww7uszsx6hmqj6vqkqptvdssm 10stake --gas="auto" --from wallet1  --keyring-backend test --fees 1000stake
```

The error produced is this:
```shell
Error: rpc error: code = Unknown desc = rpc error: code = Unknown desc = recovered: Division by zero

stack:
goroutine 361 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x5e
[github.com/cosmos/cosmos-sdk/baseapp.NewBaseApp.newDefaultRecoveryMiddleware.func3({0x1e4c380](http://github.com/cosmos/cosmos-sdk/baseapp.NewBaseApp.newDefaultRecoveryMiddleware.func3(%7B0x1e4c380)?, 0x2d80db0})
	[github.com/cosmos/cosmos-sdk@v0.47.6/baseapp/recovery.go:71](http://github.com/cosmos/cosmos-sdk@v0.47.6/baseapp/recovery.go:71) +0x26
[github.com/cosmos/cosmos-sdk/baseapp.NewBaseApp.newDefaultRecoveryMiddleware.newRecoveryMiddleware.func5({0x1e4c380](http://github.com/cosmos/cosmos-sdk/baseapp.NewBaseApp.newDefaultRecoveryMiddleware.newRecoveryMiddleware.func5(%7B0x1e4c380)?, 0x2d80db0?})
	[github.com/cosmos/cosmos-sdk@v0.47.6/baseapp/recovery.go:39](http://github.com/cosmos/cosmos-sdk@v0.47.6/baseapp/recovery.go:39) +0x2d
[github.com/cosmos/cosmos-sdk/baseapp.processRecovery({0x1e4c380](http://github.com/cosmos/cosmos-sdk/baseapp.processRecovery(%7B0x1e4c380), 0x2d80db0}, 0x1e4c380?)
	[github.com/cosmos/cosmos-sdk@v0.47.6/baseapp/recovery.go:28](http://github.com/cosmos/cosmos-sdk@v0.47.6/baseapp/recovery.go:28) +0x2f
[github.com/cosmos/cosmos-sdk/baseapp.processRecovery({0x1e4c380](http://github.com/cosmos/cosmos-sdk/baseapp.processRecovery(%7B0x1e4c380), 0x2d80db0}, 0x1e4c380?)
	[github.com/cosmos/cosmos-sdk@v0.47.6/baseapp/recovery.go:33](http://github.com/cosmos/cosmos-sdk@v0.47.6/baseapp/recovery.go:33) +0x53
[github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx.func1()](http://github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx.func1())
	[github.com/cosmos/cosmos-sdk@v0.47.6/baseapp/baseapp.go:646](http://github.com/cosmos/cosmos-sdk@v0.47.6/baseapp/baseapp.go:646) +0x12d
panic({0x1e4c380?, 0x2d80db0?})
	runtime/panic.go:920 +0x270
[github.com/cosmos/cosmos-sdk/x/auth/ante.SetUpContextDecorator.AnteHandle.func1()](http://github.com/cosmos/cosmos-sdk/x/auth/ante.SetUpContextDecorator.AnteHandle.func1())
	[github.com/cosmos/cosmos-sdk@v0.47.6/x/auth/ante/setup.go:65](http://github.com/cosmos/cosmos-sdk@v0.47.6/x/auth/ante/setup.go:65) +0x1e5
panic({0x1e4c380?, 0x2d80db0?})
	runtime/panic.go:914 +0x21f
[cosmossdk.io/math.Int.Quo({0x16?}](http://cosmossdk.io/math.Int.Quo(%7B0x16?}), {0x1e2a520?})
	[cosmossdk.io/math@v1.2.0/int.go:313](http://cosmossdk.io/math@v1.2.0/int.go:313) +0x6f
[cosmossdk.io/math.Int.QuoRaw({0x0?}](http://cosmossdk.io/math.Int.QuoRaw(%7B0x0?}), 0x2268fac?)
	[cosmossdk.io/math@v1.2.0/int.go:320](http://cosmossdk.io/math@v1.2.0/int.go:320) +0x74
[github.com/skip-mev/feemarket/x/feemarket/ante.getTxPriority({0xc000803800](http://github.com/skip-mev/feemarket/x/feemarket/ante.getTxPriority(%7B0xc000803800)?, 0x1, 0x1?}, 0xc0000b7c20?)
	[github.com/skip-mev/feemarket@v0.0.0-00010101000000-000000000000/x/feemarket/ante/fee.go:125](http://github.com/skip-mev/feemarket@v0.0.0-00010101000000-000000000000/x/feemarket/ante/fee.go:125) +0x6f
[github.com/skip-mev/feemarket/x/feemarket/ante.FeeMarketCheckDecorator.AnteHandle({{_](http://github.com/skip-mev/feemarket/x/feemarket/ante.FeeMarketCheckDecorator.AnteHandle(%7B%7B_), _}}, {{0x2da71a0, 0x4098ac0}, {0x2db8360, 0xc000981940}, {{0xb, 0x0}, {0xc004947df0, 0x9}, ...}, ...}, ...)
	[github.com/skip-mev/feemarket@v0.0.0-00010101000000-000000000000/x/feemarket/ante/fee.go:65](http://github.com/skip-mev/feemarket@v0.0.0-00010101000000-000000000000/x/feemarket/ante/fee.go:65) +0x465
```

Please advise how to proceed with this issue. Running with `--gas=auto` is an important feature when estimating gas (running Txs in simulate mode).

### Possible solution
Maybe something like this could work:
```diff
func (dfd FeeMarketCheckDecorator) AnteHandle(ctx sdk.Context, tx sdk.Tx, simulate bool, next sdk.AnteHandler) (sdk.Context, error) {

-	if !simulate {
-		fee, _, err = CheckTxFees(ctx, minGasPrices, feeTx, true)
-		if err != nil {
-			return ctx, errorsmod.Wrapf(err, "error checking fee")
-		}
-	}
-
-	minGasPricesDecCoins := sdk.NewDecCoinsFromCoins(minGasPrices...)
-	newCtx := ctx.WithPriority(getTxPriority(fee, int64(gas))).WithMinGasPrices(minGasPricesDecCoins)
-	return next(newCtx, tx, simulate)
-}
+	minGasPricesDecCoins := sdk.NewDecCoinsFromCoins(minGasPrices...)
+	if !simulate {
+		fee, _, err = CheckTxFees(ctx, minGasPrices, feeTx, true)
+		if err != nil {
+			return ctx, errorsmod.Wrapf(err, "error checking fee")
+		}
+		newCtx := ctx.WithPriority(getTxPriority(fee, int64(gas))).WithMinGasPrices(minGasPricesDecCoins)
+		return next(newCtx, tx, simulate)
+	}
+
+	ctx = ctx.WithMinGasPrices(minGasPricesDecCoins)
+	return next(ctx, tx, simulate)
+}
```

**Comment by MSalopek** [comment]
PR is here: https://github.com/skip-mev/feemarket/pull/70
